### ISSUE TITLE
age at death

### ISSUE THREAD

**Issue by IvanWilli** [willekens/VirtualPop#4]
Hi! Thanks for this package, I started to explore it and looks great! For sure will help a lot of people working on kinship topics.
One small doubt is about $x_D$ value in the available dataset `dataLH`, my first thought is that should be equal to $ddate-bdate$ but is not. 
Something I don´t undesrtand about logic?
Thanks again!

**Comment by IvanWilli** [comment]
Related to this, the age distribution at death seems a bit strange with default data `data("dataLH")`:
``dataLH %>%
  filter(gen==1) %>%
  count(x_D = trunc(x_D)) %>% 
  ggplot(aes(x_D, n)) +
  geom_line()
  ``
![image](https://user-images.githubusercontent.com/13457638/204797631-09e44418-124e-492c-b6cd-96643e23b606.png)

It looks that the piece-wise random sampling works ok, but for some reason in the default loaded data is not ok:
``
data("rates")
x_D <- msm::rpexp(n=10000,rate=rates$ASDR[,"Males"],t=0:110)
hist(x_D)
``
![image](https://user-images.githubusercontent.com/13457638/204799351-fbc61c8f-6af8-46ce-a426-16a93d4ac1da.png)

**Comment by willekens** [comment]
> Hi! Thanks for this package, I started to explore it and looks great! For sure will help a lot of people working on kinship topics.
> One small doubt is about 
> x
> D
>  value in the available dataset `dataLH`, my first thought is that should be equal to 
> d
> d
> a
> t
> e
> −
> b
> d
> a
> t
> e
>  but is not.
> Something I don´t undesrtand about logic?
> Thanks again!

Thanks. I reproduced the error and will look into it. Thanks for reporting. Frans

**Comment by willekens** [comment]
> > Hi! Thanks for this package, I started to explore it and looks great! For sure will help a lot of people working on kinship topics.
> > One small doubt is about
> > x
> > D
> > value in the available dataset `dataLH`, my first thought is that should be equal to
> > d
> > d
> > a
> > t
> > e
> > −
> > b
> > d
> > a
> > t
> > e
> > but is not.
> > Something I don´t undesrtand about logic?
> > Thanks again!
> 
> Thanks. I reproduced the error and will look into it. Thanks for reporting. Frans

The problems seems to be that x_D for gen 1 is the current age of virtual individuals, not their age at death (see p.7 of the Tutorial). I need to replace the sample data with a correct version. 

For the second and higher generations, x_D is the age at death. 

Thank you for noticing.

**Comment by willekens** [comment]
The default data distributed with the Families package has the correct x_D.

**Comment by IvanWilli** [comment]
Right. thanks!

**Comment by willekens** [comment]
?Dear Iván


I am revising and updating the package Families which depends on VirtualPop. Do you have comments on the package and/or suggestions? They would be very welcome.


With best wishes


Frans



________________________________
